version: "2"

services:
  db:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=app_database
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=wR66mDHX3V2bKhkL
    ports:
      - 5432:5432

  app:
    tty: true
    build: .
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:Q1tT/OXp536Demnpa34ucFSjLSX5Hoh7wcYjNFPhhWI=
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_USERNAME=app_user
      - DB_DATABASE=app_database
      - DB_PASSWORD=wR66mDHX3V2bKhkL
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    privileged: true
